name: 'Build vmtest CI image'
description: 'build and push docker image'
inputs:
  dockercontext:
    description: 'Directory with Dockerfile and supplementary files'
    required: true
    default: ''
  image-suffix:
    description: 'Suffix of the image name'
    required: true
    default: ''
  login-password:
    description: 'ghcr.io login password'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ inputs.login-password }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ inputs.image-suffix }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.dockercontext }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

