version: 2

templates:
  golang-template: &golang-template
    docker:
      - image: cimg/go:1.20
    working_directory: /home/circleci/go/src/github.com/hugelgupf/vmtest

  integration-amd64-template: &integration-amd64-template
    docker:
      - image: ghcr.io/hugelgupf/vmtest/ci-amd64:main
    working_directory: /home/circleci/go/src/github.com/hugelgupf/vmtest

  integration-arm64-template: &integration-arm64-template
    docker:
      - image: ghcr.io/hugelgupf/vmtest/ci-arm64:main
    working_directory: /home/circleci/go/src/github.com/hugelgupf/vmtest
    environment:
      - VMTEST_ARCH: arm64

  integration-arm-template: &integration-arm-template
    docker:
      - image: ghcr.io/hugelgupf/vmtest/ci-arm:main
    working_directory: /home/circleci/go/src/github.com/hugelgupf/vmtest
    environment:
      - VMTEST_ARCH: arm

  test-template: &test-template
    steps:
      - checkout
      - run: go test -v -p=1 ./...

workflows:
  version: 2
  test:
    jobs:
      - build
      - test-arm64:
          requires:
            - build
      - test-amd64:
          requires:
            - build
      - test-arm:
          requires:
            - build

jobs:
  build:
    <<: *golang-template
    steps:
      - checkout
      - run: go env
      - run: go vet ./...
      - run:
          name: go mod tidy
          command: |
            go mod tidy
            go mod verify
            git status
            if [[ -n "$(git status --porcelain .)" ]]; then
              echo 'go.mod/go.sum is out-of-date: run `go mod tidy` in the right module directories (see git status) and then check in the changes'
              echo 'If `go mod tidy` results in no changes, make sure you are using the latest relase of Go'
              git status --porcelain .
              exit 1
            fi
      - run:
          name: gofmt
          command: test -z "$(gofmt -s -l $(find -name '*.go'))"
      - run: go build ./...

  test-amd64:
    <<: [*test-template, *integration-amd64-template]

  test-arm64:
    <<: [*test-template, *integration-arm64-template]

  test-arm:
    <<: [*test-template, *integration-arm-template]
