name: Publish kernel images

on:
  push:
    paths:
      - 'images/arm/*'
      - 'images/arm64/*'
      - 'images/amd64/*'
      - 'images/kernel-arm/*'
      - 'images/kernel-arm64/*'
      - 'images/kernel-amd64/*'
      - '.github/workflows/kernel-images.yml'
      - '.github/actions/build-vmtest-ci-image.yml'
    branches: ['main']
    tags: ['v*']
  pull_request:
    paths:
      - 'images/arm/*'
      - 'images/arm64/*'
      - 'images/amd64/*'
      - 'images/kernel-arm/*'
      - 'images/kernel-arm64/*'
      - 'images/kernel-amd64/*'
      - '.github/workflows/kernel-images.yml'
      - '.github/actions/build-vmtest-ci-image.yml'
    branches: ['main']

# Cancel running workflows on new push to a PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io

jobs:
  arm-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 'Build Arm image'
        uses: ./.github/actions/build-vmtest-ci-image
        with:
          dockercontext: ./images/arm
          image-suffix: ci-arm
          login-password: ${{ secrets.GITHUB_TOKEN }}

  kernel-arm-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 'Build Kernel-only Arm image'
        uses: ./.github/actions/build-vmtest-ci-image
        with:
          dockercontext: ./images/kernel-arm
          image-suffix: kernel-arm
          login-password: ${{ secrets.GITHUB_TOKEN }}

  amd64-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 'Build AMD64 image'
        uses: ./.github/actions/build-vmtest-ci-image
        with:
          dockercontext: ./images/amd64
          image-suffix: ci-amd64
          login-password: ${{ secrets.GITHUB_TOKEN }}

  kernel-amd64-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 'Build Kernel-only AMD64 image'
        uses: ./.github/actions/build-vmtest-ci-image
        with:
          dockercontext: ./images/kernel-amd64
          image-suffix: kernel-amd64
          login-password: ${{ secrets.GITHUB_TOKEN }}

  arm64-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 'Build Arm64 image'
        uses: ./.github/actions/build-vmtest-ci-image
        with:
          dockercontext: ./images/arm64
          image-suffix: ci-arm64
          login-password: ${{ secrets.GITHUB_TOKEN }}

  kernel-arm64-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 'Build Kernel-only Arm64 image'
        uses: ./.github/actions/build-vmtest-ci-image
        with:
          dockercontext: ./images/kernel-arm64
          image-suffix: kernel-arm64
          login-password: ${{ secrets.GITHUB_TOKEN }}
