name: Publish kernel images

on:
  push:
    paths:
      - 'images/kernel-arm/*'
      - 'images/kernel-arm64/*'
      - 'images/kernel-amd64/*'
      - 'images/kernel-riscv64/*'
      - '.github/workflows/kernel-images.yml'
      - '.github/actions/build-vmtest-ci-image.yml'
    branches: ['main']
    tags: ['v*']
  pull_request:
    paths:
      - 'images/kernel-arm/*'
      - 'images/kernel-arm64/*'
      - 'images/kernel-amd64/*'
      - 'images/kernel-riscv64/*'
      - '.github/workflows/kernel-images.yml'
      - '.github/actions/build-vmtest-ci-image.yml'
    branches: ['main']

# Cancel running workflows on new push to a PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io

jobs:
  kernel-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        arch: [ 'amd64', 'arm', 'arm64', 'riscv64' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 'Build kernel image'
        uses: ./.github/actions/build-vmtest-ci-image
        with:
          dockercontext: ./images/kernel-${{ matrix.arch }}
          image-suffix: kernel-${{ matrix.arch }}
          login-password: ${{ secrets.GITHUB_TOKEN }}
